---
- name: Create the ondemand_exporter group
  ansible.builtin.group:
    name: "{{ ondemand_exporter_system_group }}"
    state: present
    system: true
  when: ondemand_exporter_system_group != "root"

- name: Create the ondemand_exporter user
  ansible.builtin.user:
    name: "{{ ondemand_exporter_system_user }}"
    groups: "{{ ondemand_exporter_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    home: /
  when: ondemand_exporter_system_user != "root"

- name: Get binary
  when:
    - not ondemand_exporter_skip_install
  block:

    - name: Download ondemand_exporter binary to local folder
      become: false
      ansible.builtin.get_url:
        url: "{{ ondemand_exporter_binary_url }}"
        dest: "{{ ondemand_exporter_archive_path }}/ondemand_exporter-{{ ondemand_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        checksum: "sha256:{{ __ondemand_exporter_checksum }}"
        mode: '0644'
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false

    - name: Unpack ondemand_exporter binary
      become: false
      ansible.builtin.unarchive:
        src: "{{ ondemand_exporter_archive_path }}/ondemand_exporter-{{ ondemand_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        dest: "{{ ondemand_exporter_archive_path }}"
        creates: "{{ ondemand_exporter_archive_path }}/ondemand_exporter-{{ ondemand_exporter_version }}.linux-{{ go_arch }}/ondemand_exporter"
      delegate_to: localhost
      check_mode: false

    - name: Propagate ondemand_exporter binaries
      ansible.builtin.copy:
        src: "{{ ondemand_exporter_archive_path }}/ondemand_exporter-{{ ondemand_exporter_version }}.linux-{{ go_arch }}/ondemand_exporter"
        dest: "{{ ondemand_exporter_binary_install_dir }}/ondemand_exporter"
        mode: 0755
        owner: root
        group: root
      notify: restart ondemand_exporter
      when: not ansible_check_mode

#- name: Propagate locally distributed ondemand_exporter binary
#  ansible.builtin.copy:
#    src: "{{ ondemand_exporter_binary_local_dir }}/ondemand_exporter"
#    dest: "{{ ondemand_exporter_binary_install_dir }}/ondemand_exporter"
#    mode: 0755
#    owner: root
#    group: root
#  when:
#    - ondemand_exporter_binary_local_dir | length > 0
#    - not ondemand_exporter_skip_install
#  notify: restart ondemand_exporter

#- name: Copy the sudoers template for {{ ondemand_exporter_system_user }}
#  ansible.builtin.template:
#    src: "templates/sudoers.j2"
#    dest: "/etc/sudoers.d/ondemand_exporter"
#    mode: 0440
#    owner: root
#    group: root
#
#- name: Copy the apache status report vhost template if we intend to monitor it
#  ansible.builtin.template:
#    src: "templates/apache.conf"
#    dest: "/etc/sudoers.d/ondemand_exporter"
#    mode: 0440
#    owner: root
#    group: root

